#! /bin/sh

# shell commands
feh --bg-scale ~/.config/bspwm/tokyodark.jpeg
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
$HOME/.config/polybar/launch.sh
$HOME/.config/picom/launch.sh
dunst &
#xrandr --output eDP-1 --primary --mode 1600x900 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
pgrep -x sxhkd >/dev/null || sxhkd &

# for touchpad
synclient HorizEdgeScroll=1
synclient HorizTwoFingerScroll=1
synclient MaxSpeed=2.75
synclient AccelFactor=0.09
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding 20

bspc config window_gap 5

bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

bspc config split_ratio 0.50
bspc config gapless_monocle false

# wm rules
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Nemo desktop='^9' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^4' follow=on
bspc rule -a Code desktop='^10' follow=on
bspc rule -a Caprine desktop='^8' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true
